AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  producer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: producer/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::059429486568:role/adminlambda'
      CodeUri: .debug/
